// <auto-generated />
using System;
using HondenRescue.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HondenRescue.Migrations
{
    [DbContext(typeof(HRContext))]
    partial class HRContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HondenRescue.Models.Eigenaar", b =>
                {
                    b.Property<int>("EigenaarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EigenaarId"), 1L, 1);

                    b.Property<string>("Familienaam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Voornaam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EigenaarId");

                    b.ToTable("Eigenaar", (string)null);
                });

            modelBuilder.Entity("HondenRescue.Models.Hond", b =>
                {
                    b.Property<int>("HondId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HondId"), 1L, 1);

                    b.Property<string>("FotoNaam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Geboortedatum")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Gechipt")
                        .HasColumnType("bit");

                    b.Property<int>("Geslacht")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LaatsteVaccinatieDatum")
                        .HasColumnType("datetime2");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opmerkingen")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HondId");

                    b.ToTable("Hond", (string)null);
                });

            modelBuilder.Entity("HondenRescue.Models.HondEigenaar", b =>
                {
                    b.Property<int>("HondEigenaarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HondEigenaarId"), 1L, 1);

                    b.Property<int>("EigenaarId")
                        .HasColumnType("int");

                    b.Property<int>("HondId")
                        .HasColumnType("int");

                    b.HasKey("HondEigenaarId");

                    b.HasIndex("EigenaarId");

                    b.HasIndex("HondId");

                    b.ToTable("HondEigenaar", (string)null);
                });

            modelBuilder.Entity("HondenRescue.Models.HondEigenaar", b =>
                {
                    b.HasOne("HondenRescue.Models.Eigenaar", "Eigenaar")
                        .WithMany("HondEigenaren")
                        .HasForeignKey("EigenaarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HondenRescue.Models.Hond", "Hond")
                        .WithMany("HondEigenaren")
                        .HasForeignKey("HondId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Eigenaar");

                    b.Navigation("Hond");
                });

            modelBuilder.Entity("HondenRescue.Models.Eigenaar", b =>
                {
                    b.Navigation("HondEigenaren");
                });

            modelBuilder.Entity("HondenRescue.Models.Hond", b =>
                {
                    b.Navigation("HondEigenaren");
                });
#pragma warning restore 612, 618
        }
    }
}
